### ISSUE TITLE
About the evaluation codes.

### ISSUE THREAD

**Issue by RunsenXu** [sled-group/chat-with-nerf#26]
Dear author,

Thanks for your great work. I wonder do you plan to release the evaluation codes and scripts to reproduce the quantitative results in your LLM-Grounder paper?

Best,
Runsen

**Comment by XuweiyiChen** [comment]
Greetings,

We have just released the evaluated code and preprocessed data for the paper.

Please use the none-interactive version of the prompt and fix the path with your downloaded data. Note to also estimate the budget since GPT-4 is used for evaluations.

Best Regards,
Xuweiyi Chen
