### ISSUE TITLE
Question about the possibility of 3D Gaussian Splatting

### ISSUE THREAD

**Issue by Ryan-ZL-Lin** [sled-group/chat-with-nerf#27]
Hi
    First of all, thanks for your amazing idea and the implementation, I'm very excited to test it out. However, since 3D-Gaussian-Splatting related papers have been published a lot last year, I'm also quite curious about the possibility of "Chat-with-GS", is it possible? or...the possibility for the integration with SMERF (https://smerf-3d.github.io/)

**Comment by XuweiyiChen** [comment]
It is indeed possible to incorporate GS. I imagine if we have language-embedded GS, the preprocessing part will be much more straightforward.
