### ISSUE TITLE
Env Setting: python3.10 or python3.8

### ISSUE THREAD

**Issue by adrianJW421** [sled-group/chat-with-nerf#31]
Thanks for releasing such great work. I'd like to know if the deployment of the demo is based on python3.10 instead of python3.8 as mentioned in the README, because I found many codes are based on python3.10 supports. For example, class Session in  chat-with-nerf/chat_with_nerf/chat/session.py

**Comment by jedyang97** [comment]
Thanks for spotting this. For the demo, we deployed using Docker, as the environment for this work is indeed a bit tricky to set up.
