### ISSUE TITLE
How to get the 2D image?

### ISSUE THREAD

**Issue by Leon1207** [sled-group/chat-with-nerf#33]
What a great work!
Could you please share how you generate the 2D image in your demo, when the candidates were grounded?

**Comment by jedyang97** [comment]
Hi @Leon1207 ,

The 2D pics in the demo were rendered from LERF - so 2D pics are only available when using LERF as the vision backbone (as opposed to OpenScene). But we decided to only include it in the demo and not the paper b/c the visual quality is not that good. but you are welcome to further explore this direction!
